"""empty message

Revision ID: a5895d52e520
Revises: 
Create Date: 2021-10-01 17:32:14.744924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5895d52e520'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultation',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('doctor', sa.String(length=200), nullable=True),
    sa.Column('appointment', sa.Date(), nullable=True),
    sa.Column('type', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('appointment_location', sa.String(length=200), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('consultation')
    # ### end Alembic commands ###
